import GlobalNav from "@/components/globalNav";
import ClientOnlyComponent from "./client-only-component";
import "../styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientOnlyComponent />
        <GlobalNav />
        {children}
      </body>
    </html>
  );
}
